# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aad13742bb96924e6a70ea4f2be4288de6ed252508cc854b562760b9c8cf40fe5434842bbb683a3d7261a98afbc475fb3eab1e4c84caa7dc671a9998f87a6d9

test:
  secret_key_base: 97dbf09c36a7c46f48fd9f32a3da11e17a7812a70d3bcc64e44d25a47978338532b7f467261d19e0ef15020aa50bdf02ba06803fc9f7eaa0db5e96413189dff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
